name = "PropertyDicts"
uuid = "f8a19df8-e894-5f55-a973-672c1158cbca"
license = "MIT"
version = "0.2.1"

[compat]
julia = "1.6"

[extras]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["OrderedCollections", "Test"]
